/* ../source/linear_sys.c */
void make_voltage_geometry_matrix(boundary *b, matrix *vgm);
void fill_voltage_geometry_matrix(int offset_i, int offset_j, path *path_i, path *path_j, matrix *vgm);
void make_current_geometry_matrix(boundary *b, matrix *cgm);
void fill_current_geometry_matrix(int offset_i, int offset_j, path *path_i, path *path_j, matrix *cgm);
void make_diagonal_matrix(boundary *b, matrix *dm);
void fill_diagonal_matrix(int offset_i, int offset_j, path *path_i, path *path_j, matrix *dm);
void empty_diagonal_matrix(int offset_i, int offset_j, path *path_i, path *path_j, matrix *dm);
void make_voltage_geometry_vector(coordinates P, boundary *b, matrix *vgv);
void fill_voltage_geometry_vector(coordinates P, int offset_j, path *path_j, matrix *vgv);
void make_current_geometry_vector(coordinates P, boundary *b, matrix *cgv);
void fill_current_geometry_vector(coordinates P, int offset_j, path *path_j, matrix *cgv);
void make_kcl_geometry_vector(boundary *b, matrix *kcl);
void fill_kcl_geometry_vector(int offset_j, path *path_j, matrix *kcl);
void make_co_voltage_geometry_vector(coordinates P, boundary *b, co_matrix *co_vgv);
void fill_co_voltage_geometry_vector(coordinates P, int offset_j, path *path_j, co_matrix *co_vgv);
void make_co_current_geometry_vector(coordinates P, boundary *b, co_matrix *co_cgv);
void fill_co_current_geometry_vector(coordinates P, int offset_j, path *path_j, co_matrix *co_cgv);
void make_ten_voltage_geometry_vector(coordinates P, boundary *b, ten_matrix *ten_vgv);
void fill_ten_voltage_geometry_vector(coordinates P, int offset_j, path *path_j, ten_matrix *ten_vgv);
void make_ten_current_geometry_vector(coordinates P, boundary *b, ten_matrix *ten_cgv);
void fill_ten_current_geometry_vector(coordinates P, int offset_j, path *path_j, ten_matrix *ten_cgv);
void p2c_2coeff(double v, double w, double *a0, double *a1);
void p2c_4coeff(double j, double k, double l, double m, double *a0, double *a1, double *a2, double *a3);
void p2c_2basis(double Vterm, double Wterm, double *A0, double *A1);
void p2c_4basis(double Jterm, double Kterm, double Lterm, double Mterm, double *A0, double *A1, double *A2, double *A3);
void p2c_2basis_co(coordinates Vterm, coordinates Wterm, coordinates A0, coordinates A1);
void p2c_4basis_co(coordinates Jterm, coordinates Kterm, coordinates Lterm, coordinates Mterm, coordinates A0, coordinates A1, coordinates A2, coordinates A3);
void p2c_2basis_ten(tensor Vterm, tensor Wterm, tensor A0, tensor A1);
void p2c_4basis_ten(tensor Jterm, tensor Kterm, tensor Lterm, tensor Mterm, tensor A0, tensor A1, tensor A2, tensor A3);
