/* ../source/matrix.c */
void set_inversion_method(int method);
int get_inversion_method(void);
matrix *create_matrix(int rows, int columns);
void attach_matrix(matrix *x, int rows, int columns, double *data);
matrix *destroy_matrix(matrix *x);
void check_matrix_index(matrix *x, int i, int j);
void check_invert(matrix *x);
void check_size(matrix *a, matrix *b);
void check_size_row(matrix *a, matrix *b);
void check_collapse_size(matrix *a, matrix *b);
void check_memory(matrix *x);
void check_add_shape(matrix *a, matrix *b);
void check_multiply_shape(matrix *a, matrix *b);
void check_multiply_size(matrix *a, matrix *b, matrix *x);
void check_invert_shape(matrix *a);
int get_num_columns(matrix *x);
int get_num_rows(matrix *x);
double *startof_matrix(matrix *x);
double *after_matrix(matrix *x);
void put_matrix_element(matrix *x, int i, int j, double value);
double get_matrix_element(matrix *x, int i, int j);
void put_block_matrix_element(matrix *x, int offset_i, int offset_j, int i, int j, double value);
double get_block_matrix_element(matrix *x, int offset_i, int offset_j, int i, int j);
void transpose_matrix(matrix *a, matrix *x);
void add_matrix(matrix *a, matrix *b, matrix *x);
void subtract_matrix(matrix *a, matrix *b, matrix *x);
void scale_matrix(double s, matrix *a, matrix *x);
void zero_last_matrix_row(matrix *a);
void fill_last_matrix_row(matrix *a, matrix *x);
void copy_matrix(matrix *a, matrix *x);
void transpose(double *A, double *B, int n);
void matmul(matrix *a, matrix *b, matrix *x);
void multiply_matrix(matrix *a, matrix *b, matrix *x);
void multiply_matrix_org(matrix *a, matrix *b, matrix *x);
void multiply_matrix_(matrix *a, matrix *b, matrix *x);
void multiply_element_row(matrix *a, matrix *b, int row_a, matrix *x);
void multiply_element_column(matrix *a, matrix *b, int row_a, int column_b, matrix *x);
void invert_matrix(matrix *a, matrix *x);
void invert_this_matrix(matrix *a);
void reduce_column(matrix *a, int col);
void reduce_row(matrix *a, int row, int pivot);
void scale_row(matrix *a, int row);
void show_matrix_info(matrix *x);
void show_matrix(matrix *x);
void show_matrix1(matrix *x);
void show_matrix2_(matrix *x);
void show_matrix2(matrix *x);
