/* ../source/terms.c */
double Vterm_PonS(double x, double y1, double y2);
double Wterm_PonS(double x, double y1, double y2);
double Jterm_PonS(double x, double y1, double y2);
double Kterm_PonS(double x, double y1, double y2);
double Lterm_PonS(double x, double y1, double y2);
double Mterm_PonS(double x, double y1, double y2);
double Uj(double y1, double y2);
double Uk(double y1, double y2);
double Ul(double y1, double y2);
double Um(double y1, double y2);
double Vterm_PoffS(double x, double y1, double y2);
double Wterm_PoffS(double x, double y1, double y2);
double Jterm_PoffS(double x, double y1, double y2);
double Kterm_PoffS(double x, double y1, double y2);
double Lterm_PoffS(double x, double y1, double y2);
double Mterm_PoffS(double x, double y1, double y2);
double Tv(double x, double y1, double y2);
double Tw(double x, double y1, double y2);
double Tj(double x, double y1, double y2);
double Tk(double x, double y1, double y2);
double Tl(double x, double y1, double y2);
double Tm(double x, double y1, double y2);
void V1(double x, double y1, double y2, coordinates v);
void W1(double x, double y1, double y2, coordinates w);
void J1(double x, double y1, double y2, coordinates j);
void K1(double x, double y1, double y2, coordinates k);
void L1(double x, double y1, double y2, coordinates l);
void M1(double x, double y1, double y2, coordinates m);
double X1v(double x, double y1, double y2);
double Y1v(double x, double y1, double y2);
double X1w(double x, double y1, double y2);
double Y1w(double x, double y1, double y2);
double X1j(double x, double y1, double y2);
double Y1j(double x, double y1, double y2);
double X1k(double x, double y1, double y2);
double Y1k(double x, double y1, double y2);
double X1l(double x, double y1, double y2);
double Y1l(double x, double y1, double y2);
double X1m(double x, double y1, double y2);
double Y1m(double x, double y1, double y2);
void V2(double x, double y1, double y2, tensor v);
void W2(double x, double y1, double y2, tensor w);
void J2(double x, double y1, double y2, tensor j);
void K2(double x, double y1, double y2, tensor k);
void L2(double x, double y1, double y2, tensor l);
void M2(double x, double y1, double y2, tensor m);
double X2v(double x, double y1, double y2);
double Z2v(double x, double y1, double y2);
double X2w(double x, double y1, double y2);
double Z2w(double x, double y1, double y2);
double X2j(double x, double y1, double y2);
double Z2j(double x, double y1, double y2);
double X2k(double x, double y1, double y2);
double Z2k(double x, double y1, double y2);
double X2l(double x, double y1, double y2);
double Z2l(double x, double y1, double y2);
double X2m(double x, double y1, double y2);
double Z2m(double x, double y1, double y2);
